INSERT INTO job (name, script_path, script_params, channel, cron_expression, next_script1, next_script2, active, last_log, last_exit_code, sequence) VALUES
  ('Daily 5m Stream', 'orchestrators/run_pipeline_and_stream.sh', '0.083 --tag lofi --post-twitter --post-instagram', 'default', '0 0 0 * * *', NULL, NULL, true, NULL, NULL, 1),
  ('Daily 5m Upload', 'orchestrators/run_pipeline_and_upload.sh', '0.083 --tag lofi --post-twitter', 'default', '0 0 15 * * *', NULL, NULL, true, NULL, NULL, 2),
  ('Daily 5m Upload Test', 'orchestrators/run_pipeline_and_upload.sh', '0.083 --tag lofi --post-twitter', 'default', '0 30 3 * * *', NULL, NULL, true, NULL, NULL, 3),
  ('Daily Tweet - LoFi', 'publishers/twitter/post_to_twitter_simple.py', 'lofi', 'default', '0 30 12 * * *', NULL, NULL, true, NULL, NULL, 4),
  ('Daily Tweet - Horoscope Aries', 'publishers/twitter/post_to_twitter_simple.py', 'horoscope aries', 'default', '0 0 9 * * *', NULL, NULL, true, NULL, NULL, 5),
  ('Daily Tweet - Horoscope Taurus', 'publishers/twitter/post_to_twitter_simple.py', 'horoscope taurus', 'default', '0 15 9 * * *', NULL, NULL, true, NULL, NULL, 6),
  ('Daily Tweet - Horoscope Gemini', 'publishers/twitter/post_to_twitter_simple.py', 'horoscope gemini', 'default', '0 30 9 * * *', NULL, NULL, true, NULL, NULL, 7),
  ('Daily Tweet - Horoscope Cancer', 'publishers/twitter/post_to_twitter_simple.py', 'horoscope cancer', 'default', '0 45 9 * * *', NULL, NULL, true, NULL, NULL, 8),
  ('Daily Tweet - Horoscope Leo', 'publishers/twitter/post_to_twitter_simple.py', 'horoscope leo', 'default', '0 0 10 * * *', NULL, NULL, true, NULL, NULL, 9),
  ('Daily Tweet - Horoscope Virgo', 'publishers/twitter/post_to_twitter_simple.py', 'horoscope virgo', 'default', '0 15 10 * * *', NULL, NULL, true, NULL, NULL, 10),
  ('Daily Tweet - Horoscope Libra', 'publishers/twitter/post_to_twitter_simple.py', 'horoscope libra', 'default', '0 30 10 * * *', NULL, NULL, true, NULL, NULL, 11),
  ('Daily Tweet - Horoscope Scorpio', 'publishers/twitter/post_to_twitter_simple.py', 'horoscope scorpio', 'default', '0 45 10 * * *', NULL, NULL, true, NULL, NULL, 12),
  ('Daily Tweet - Horoscope Sagittarius', 'publishers/twitter/post_to_twitter_simple.py', 'horoscope sagittarius', 'default', '0 0 11 * * *', NULL, NULL, true, NULL, NULL, 13),
  ('Daily Tweet - Horoscope Capricorn', 'publishers/twitter/post_to_twitter_simple.py', 'horoscope capricorn', 'default', '0 15 11 * * *', NULL, NULL, true, NULL, NULL, 14),
  ('Daily Tweet - Horoscope Aquarius', 'publishers/twitter/post_to_twitter_simple.py', 'horoscope aquarius', 'default', '0 30 11 * * *', NULL, NULL, true, NULL, NULL, 15),
  ('Daily Tweet - Horoscope Pisces', 'publishers/twitter/post_to_twitter_simple.py', 'horoscope pisces', 'default', '0 45 11 * * *', NULL, NULL, true, NULL, NULL, 16),
  ('Daily Tweet - Meditation', 'publishers/twitter/post_to_twitter_simple.py', 'meditation', 'default', '0 15 7 * * *', NULL, NULL, true, NULL, NULL, 17),
  ('Daily Instagram Story', 'publishers/instagram/post_instagram_story.sh', '', 'default', '0 0 11 * * *', NULL, NULL, true, NULL, NULL, 18),
  
  -- NEW WORKFLOW ARCHITECTURE JOBS
  ('Video Upload - LoFi', 'orchestrators/run_workflow.sh', 'video_upload default lofi', 'default', '0 0 */6 * * *', NULL, NULL, true, NULL, NULL, 19),
  ('Social Only - Horoscope', 'orchestrators/run_workflow.sh', 'social_only minimal horoscope zodiac_sign=leo', 'default', '0 30 14 * * *', NULL, NULL, true, NULL, NULL, 20),
  ('Full Pipeline - Meditation', 'orchestrators/run_workflow.sh', 'full_pipeline default meditation', 'default', '0 0 18 * * *', NULL, NULL, true, NULL, NULL, 21),
  ('Quick Social - LoFi', 'orchestrators/quick_social_post.sh', 'lofi', 'default', '0 */3 * * * *', NULL, NULL, true, NULL, NULL, 22),
  ('Stream Workflow - LoFi', 'orchestrators/run_workflow.sh', 'stream_workflow youtube_only lofi duration=7200', 'default', '0 0 */8 * * *', NULL, NULL, true, NULL, NULL, 23);
